<?xml version="1.0" encoding="us-ascii"?>
<cinematic scenariofile="CampaignUNSC\WOW\PHXscn13\PHXscn13" soundfile="">
	<head>
		<depthoffield enabled="true" />
	</head>
	<body>
		<shot name="Shot1" camera="cinematic\cutscenes\Scenario_13\S13_Scene_03_Outro\Scene_03_Camera">
			<tag type="Chat" time="1" queue="true" duration="0" stringid="22858" sound="play_scn_13_cutter_02" talkinghead="scn_13_cutter_02" />--Chats--</shot>
	</body>
</cinematic>