<?xml version="1.0" encoding="us-ascii"?>
<cinematic scenariofile="CampaignUNSC\wow\PHXscn08\PHXscn08" soundfile="">
	<head />
	<body>
		<shot name="Shot1" camera="cinematic\cutscenes\Scenario_08\S08_Scene_03_Evacuation\Scene_03_Camera">
			<tag type="Chat" time="0" queue="true" duration="0" stringid="23132" sound="play_scn_08_forge_02" talkinghead="scn_08_forge_02" />
			<tag type="Chat" time="4" queue="true" duration="0" stringid="23451" sound="play_scn_08_serina_01" talkinghead="scn_08_serina_01" />--Chats--</shot>
	</body>
</cinematic>